name = "universelogisticsassociation"
main = "src/index.ts"        # Worker 入口
compatibility_date = "2025-12-17"

# R2 绑定
[[r2_buckets]]
binding = "universelogisticsassociationT"        # Worker 中使用的变量名
bucket_name = "universelogisticsassociation"
preview_bucket_name = "universelogisticsassociation"
